### DISCUSSION TITLE
Dataview compatable metadata?

### DISCUSSION THREAD

**Discussion by Galphanore** [hadynz/obsidian-kindle-plugin#158] [Ideas]
Is there any way to get this plugin to format the metadata it gets from kindle in a "Dataview" readable format? Basically, two colons instead of one and no apostrophe around the date. So, for instance, instead of:

```
---
kindle-sync:
  bookId: '20575'
  title: 'Dynamic Story Creation in Plain English: Drake''s Brutal Writing Advice'
  author: Maxwell Alexander Drake
  asin: B01IGSWNIO
  lastAnnotatedDate: '2019-05-01'
  bookImageUrl: 'https://m.media-amazon.com/images/I/719pcrXjAjL._SY160.jpg'
  highlightsCount: 125
---
```

It would be:

```
---
kindle-sync:
  bookId:: '20575'
  title:: 'Dynamic Story Creation in Plain English: Drake''s Brutal Writing Advice'
  author:: Maxwell Alexander Drake
  asin:: B01IGSWNIO
  lastAnnotatedDate:: 2019-05-01
  bookImageUrl:: 'https://m.media-amazon.com/images/I/719pcrXjAjL._SY160.jpg'
  highlightsCount:: 125
---
```

Maybe as a toggle? It would make importing notes and integrating them into my vault structure much easier. 

As it stands now, if I manually change it to be dataview compatible, then the next time I re-sync it will make duplicates of the book because it can't identify that the file is the same once I change the metadata.
