### ISSUE TITLE
[BUG] After syncing yaml front matter is invalid. Title has no end single quote

### ISSUE THREAD

**Issue by vertis** [hadynz/obsidian-kindle-plugin#173]
### Describe the bug
After syncing yaml front matter is invalid. 
Specifically `title: 'Record of a Spaceborn Few` has a start quote(`'`) and no end quote. 

I'll go and have a hunt to see if I can find where this is caused, but in the mean time I wanted to have a record of the problem

This is the title in my example, though I have seen other examples: https://www.amazon.com/dp/B07355XC7L

Another example that has this problem: https://www.amazon.com/dp/B007V65R54 (The Signal and the Noise)

```
---
kindle-sync:
  bookId: '30011'
  title: 'The Signal and the Noise
  author: Nate Silver
  asin: B007V65R54
  lastAnnotatedDate: '2022-02-01'
  bookImageUrl: 'https://m.media-amazon.com/images/I/81JNp1+YyqL._SY160.jpg'
  highlightsCount: 9
created: 2022-07-13T12:32:46+03:00
updated: 2022-07-13T12:32:46+03:00
---
```

### Method of syncing
- [x] Amazon Kindle Reader
- [ ] My Clippings file (please **attach file** that can be used to recreate issue)

### Expected behaviour
YAML front matter should be valid.

### Metadata
 - OS: Mac
 - Plugin version 1.5.2 and still 1.6.2
 - Obsidian version 0.14.15
